### ISSUE TITLE
NotFoundError: data/battle_model/trusty-battle-game-l; No such file or directory

### ISSUE THREAD

**Issue by ZhaoMingYang-tju** [PKU-AI-Edge/DGN#14]
打扰了，当我把项目的config放入MAgent并且开始运行multi_battle.py 遇到如下错误
Traceback (most recent call last):
  File "multi_battle.py", line 207, in <module>
    tf_model.load("data/battle_model", 0, 'trusty-battle-game-l')
  File "/home/my/MAgent/python/magent/builtin/tf_model/base.py", line 55, in load
    saver.restore(self.sess, os.path.join(dir_name, (self.subclass_name + "_%d") % epoch))
  File "/home/my/.conda/envs/tensorflow366/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1266, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/home/my/.conda/envs/tensorflow366/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/my/.conda/envs/tensorflow366/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/my/.conda/envs/tensorflow366/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 361, in get_matching_files
    return get_matching_files_v2(filename)
  File "/home/my/.conda/envs/tensorflow366/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 389, in get_matching_files_v2
    for single_filename in pattern
  File "/home/my/.conda/envs/tensorflow366/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: data/battle_model/trusty-battle-game-l; No such file or directory
请问一下原因 谢谢！

**Comment by bkzfyx** [comment]
I have also faced the problem, could you please tell me how to solve the problem?

**Comment by SriramPingali** [comment]
@ZhaoMingYang-tju .. I have faced the same issue too. Please post what you have done to resolve it.
