### ISSUE TITLE
This code can't run with requements

### ISSUE THREAD

**Issue by WoNiuHu** [PKU-AI-Edge/DGN#20]
This code can't run with requirements.    "Traceback (most recent call last):
  File "multi_battle.py", line 7, in <module>
    from keras import backend as K
  File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/__init__.py", line 4, in <module>
    from . import activations
  File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/activations.py", line 6, in <module>
    from .engine import Layer
  File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/engine/training.py", line 25, in <module>
    from .. import callbacks as cbks
  File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/callbacks.py", line 26, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
ModuleNotFoundError: No module named 'tensorflow.contrib'"

it seems that the tensorflow version or keras version can't work well. does anyone know how to fix it? thanks

**Comment by wuxuhang** [comment]
我也遇到了同样的问题，请问你现在解决了吗？谢谢

**Comment by wuxuhang** [comment]
> This code can't run with requirements. "Traceback (most recent call last):
> File "multi_battle.py", line 7, in
> from keras import backend as K
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/**init**.py", line 4, in
> from . import activations
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/activations.py", line 6, in
> from .engine import Layer
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/engine/**init**.py", line 8, in
> from .training import Model
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/engine/training.py", line 25, in
> from .. import callbacks as cbks
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/callbacks.py", line 26, in
> from tensorflow.contrib.tensorboard.plugins import projector
> ModuleNotFoundError: No module named 'tensorflow.contrib'"
> 
> it seems that the tensorflow version or keras version can't work well. does anyone know how to fix it? thanks

I have the same problem. Have you solved it now? thank you

**Comment by bkzfyx** [comment]
I use tensorflow 1.14.0 and Keras 2.2.4 to run the code

**Comment by Ppaddington** [comment]
Firstly, we need to install MAgent, https://github.com/geek-ai/MAgent.
Then, tensorflow 1.14 and Keras 2.1.2.

**Comment by xinhaoH** [comment]
> This code can't run with requirements. "Traceback (most recent call last):
> File "multi_battle.py", line 7, in
> from keras import backend as K
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/**init**.py", line 4, in
> from . import activations
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/activations.py", line 6, in
> from .engine import Layer
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/engine/**init**.py", line 8, in
> from .training import Model
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/engine/training.py", line 25, in
> from .. import callbacks as cbks
> File "/Users/huhaibing/Desktop/rl_papers_code/env/lib/python3.6/site-packages/keras/callbacks.py", line 26, in
> from tensorflow.contrib.tensorboard.plugins import projector
> ModuleNotFoundError: No module named 'tensorflow.contrib'"
> 
> it seems that the tensorflow version or keras version can't work well. does anyone know how to fix it? thanks

Firstly, we need to install MAgent, https://github.com/geek-ai/MAgent.
Then, tensorflow 1.14 and Keras 2.1.2.
