### ISSUE TITLE
对于文章中对比实验的疑问

### ISSUE THREAD

**Issue by Jarvis-K** [PKU-AI-Edge/DGN#6]
DQN和CommNet的效果似乎很差？但我按照文章设置使用DQN在Jungle中达到的结果和DGN类似，最终收敛到0.69附近。

**Comment by zhoushiyang12** [comment]
Traceback (most recent call last):
  File "DGN-master/Battle/multi_battle.py", line 324, in <module>
    q_values[j][k][actions[k][j]] =rewards[k][j] + GAMMA*np.max(target_q_values[j][k])
IndexError: index 17 is out of bounds for axis 0 with size 9


你好，我在运行Battle.py时遇到这样的问题，你有遇到吗？不知道是代码的问题，还是环境没配好。。。

**Comment by laker-sprus** [comment]
按照该代码训练，Battle的训练和测试kill-dead ratio没有到2.0以上，处于0.5左右。不知道是不是上传的代码哪里有疏漏

**Comment by laker-sprus** [comment]
According to the code，the kill-dead ratio of battle is about 0.5 after training 2000 episodes, which is far away from 2.0.  I don't know if there is any omission in the uploaded code.

**Comment by lihuiknight** [comment]
> 按照该代码训练，Battle的训练和测试kill-dead ratio没有到2.0以上，处于0.5左右。不知道是不是上传的代码哪里有疏漏

@Jarvis-K @laker-sprus   对于这种问题，作者也不会出来回答一下么？这可是北大的开源代码。

**Comment by AdagioZbc** [comment]
> DQN和CommNet的效果似乎很差？但我按照文章设置使用DQN在Jungle中达到的结果和DGN类似，最终收敛到0.69附近。

请问你的环境配置是什么？我现在还没有成功跑起来他们的代码

**Comment by sssstupid** [comment]
> Traceback (most recent call last):
> File "DGN-master/Battle/multi_battle.py", line 324, in
> q_values[j][k][actions[k][j]] =rewards[k][j] + GAMMA*np.max(target_q_values[j][k])
> IndexError: index 17 is out of bounds for axis 0 with size 9
> 
> 你好，我在运行Battle.py时遇到这样的问题，你有遇到吗？不知道是代码的问题，还是环境没配好。。。
我现在也遇到这个问题，请问你后来解决了嘛？

**Comment by laker-sprus** [comment]
你可以参考我的代码RFQ-RFAC，或者MFQ-MFAC。
这篇文章及代码不负责任，我逐行看过，涉嫌凑结果（改reward），而且代码质量太差，没有太多分析的价值。

**Comment by sssstupid** [comment]
> 你可以参考我的代码RFQ-RFAC，或者MFQ-MFAC。 这篇文章及代码不负责任，我逐行看过，涉嫌凑结果（改reward），而且代码质量太差，没有太多分析的价值。

指的是这个https://github.com/renweiya/RFQ-RFAC吗？

**Comment by deLouvre** [comment]
> 你可以参考我的代码RFQ-RFAC，或者MFQ-MFAC。 这篇文章及代码不负责任，我逐行看过，涉嫌凑结果（改reward），而且代码质量太差，没有太多分析的价值。

请问你指的是这个 https://github.com/renweiya/RFQ-RFAC 吗？

**Comment by deLouvre** [comment]
Traceback (most recent call last):
  File "multi_battle.py", line 336, in <module>
    history=model.fit(states, q_values,epochs=1,batch_size=128,verbose=0)
IndexError: index 10 is out of bounds for axis 0 with size 9
请问大家有遇到这个问题吗？如何解决呢

**Comment by Howrhy** [comment]
> 按照该代码训练，Battle的训练和测试kill-dead ratio没有到2.0以上，处于0.5左右。不知道是不是上传的代码哪里有疏漏

请问怎么测试，代码我已经跑起来并且得到了模型

**Comment by jiawweiL** [comment]
> Traceback (most recent call last):
> File "DGN-master/Battle/multi_battle.py", line 324, in
> q_values[j][k][actions[k][j]] =rewards[k][j] + GAMMA*np.max(target_q_values[j][k])
> IndexError: index 17 is out of bounds for axis 0 with size 9
> 
> 
你好，我在运行Battle.py时遇到这样的问题，你有遇到吗？不知道是代码的问题，还是环境没配好。。。
Hello, I have the same problem. Have you solved it
