### ISSUE TITLE
GAMMA = 0.96?

### ISSUE THREAD

**Issue by laker-sprus** [PKU-AI-Edge/DGN#7]
GAMMA = 0.96?

**Comment by laker-sprus** [comment]
same errors for type examples/multi_battle.py:

examples/multi_battle.py:53: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("re...)`
  model = Model(input=In_0,output=h)
Traceback (most recent call last):
  File "examples/multi_battle.py", line 134, in <module>
    m1 = MultiHeadsAttModel(l=4)#4
  File "examples/multi_battle.py", line 76, in MultiHeadsAttModel
    out = Lambda(lambda x: K.batch_dot(x[0], x[1],axes=[3,2]))([att, v])
  File "/home/laker/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/laker/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "examples/multi_battle.py", line 76, in <lambda>
    out = Lambda(lambda x: K.batch_dot(x[0], x[1],axes=[3,2]))([att, v])
  File "/home/laker/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1499, in batch_dot
    'y.shape[%d] (%d != %d).' % (axes[0], axes[1], d1, d2))
ValueError: Can not do batch_dot on inputs with shapes (None, 8, 4, 8, 4) and (None, 8, 4, 16) with axes=[3, 2]. x.shape[3] != y.shape[2] (8 != 4).
